#spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
#spring.datasource.username=postgres
#spring.datasource.password=secret
#spring.datasource.driver-class-name=org.postgresql.Driver

#INTERNAL PARA DESPLEGAR CON GITHUB EN RENDER
spring.datasource.url=jdbc:postgresql://dpg-da1lkq37uimc73aq1rm0-a/deportravel_r0kj
spring.datasource.username=deportravel_r0kj_user
spring.datasource.password=bZJPbt5jrFdE5w1XKPqAS3XsFNpKrKOb
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACIÓN JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# CONFIGURACIÓN CARGA INICIAL DE DATOS SQL
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always


#EXTERNO PARA PRUEBAS
#postgresql://deportravelbbdd_user:V8AxqALGHQxtYiuzng0Ek8QbTi0ry1k1@dpg-d15a7lre5dus739el9kg-a.frankfurt-postgres.render.com/deportravelbbdd
#spring.datasource.url=jdbc:postgresql://dpg-d15a7lre5dus739el9kg-a.frankfurt-postgres.render.com/deportravelbbdd
#spring.datasource.username=deportravelbbdd_user
#spring.datasource.password=V8AxqALGHQxtYiuzng0Ek8QbTi0ry1k1
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.name=proyecto
#spring.datasource.generate-unique-name=false

#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true

#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update

#spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

#spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
#spring.datasource.username=postgres
#spring.datasource.password=secret#
#spring.datasource.driver-class-name=org.postgresql.Driver