DELETE FROM actividades;

INSERT INTO actividades (nombre, categoria, pais, precio, fecha, descripcion, imagen) VALUES ('Yoga en Berlin', 'Yoga', 'Berlin', 150.0, '2024-10-08', 'Relájate y encuentra la paz interior mientras disfrutas de la belleza de Berlin.', '/img/Actividades/Yoga.jpg');
INSERT INTO actividades (nombre, categoria, pais, precio, fecha, descripcion, imagen) VALUES ('Trekking en Chile', 'Trekking', 'Chile', 300.0, '2024-12-08', 'Explora los paisajes de Chile mientras realizas un trekking desafiante por la cordillera de los Andes.', '/img/Actividades/Trekking.jpg');
INSERT INTO actividades (nombre, categoria, pais, precio, fecha, descripcion, imagen) VALUES ('Surf en Australia', 'Surf', 'Australia', 420.0, '2024-08-11', 'Disfruta de las mejores olas en las playas de Australia, un paraíso para los amantes del surf.', '/img/Actividades/Surf.jpg');
INSERT INTO actividades (nombre, categoria, pais, precio, fecha, descripcion, imagen) VALUES ('Montar a caballo en Mallorca', 'Montar a caballo', 'España', 120.0, '2025-09-08', 'Recorre los paisajes más hermosos de Mallorca a lomos de un caballo mientras disfrutas de su naturaleza.', '/img/Actividades/Montar a caballo.jpg');
INSERT INTO actividades (nombre, categoria, pais, precio, fecha, descripcion, imagen) VALUES ('Ciclismo en los Pirineos', 'Ciclismo', 'España', 95.0, '2024-04-20', 'Desafía tus límites en las montañas de los Pirineos mientras disfrutas de vistas impresionantes.', '/img/Actividades/Ciclismo.jpg');
INSERT INTO actividades (nombre, categoria, pais, precio, fecha, descripcion, imagen) VALUES ('Alpinismo en los Alpes', 'Alpinismo', 'Suiza', 520.0, '2024-11-11', 'Siente la adrenalina del alpinismo en los Alpes suizos, una experiencia desafiante para los más aventureros.', '/img/Actividades/Alpinismo.jpg');
INSERT INTO actividades (nombre, categoria, pais, precio, fecha, descripcion, imagen) VALUES ('Karate en China', 'Karate', 'China', 852.0, '2026-10-08', 'Perfecciona tus habilidades en Karate en China, el lugar donde nació este antiguo arte marcial.', '/img/Actividades/karate.jpg');
INSERT INTO actividades (nombre, categoria, pais, precio, fecha, descripcion, imagen) VALUES ('Fútbol en Estados Unidos', 'Fútbol', 'Estados Unidos', 963.0, '2025-06-21', 'Vive la emoción del fútbol en Estados Unidos, donde podrás entrenar y jugar en estadios de clase mundial.', '/img/Actividades/Futbol.jpg');
INSERT INTO actividades (nombre, categoria, pais, precio, fecha, descripcion, imagen) VALUES ('Baloncesto en Irlanda', 'Baloncesto', 'Irlanda', 453.0, '2026-05-19', 'Mejora tu técnica de baloncesto mientras exploras la cultura y la naturaleza irlandesa.', '/img/Actividades/Baloncesto.jpg');
INSERT INTO actividades (nombre, categoria, pais, precio, fecha, descripcion, imagen) VALUES ('Golf en Wales', 'Golf', 'Wales', 326.0, '2025-11-08', 'Juega al golf en los campos más hermosos de Gales, rodeado de paisajes naturales impresionantes.', '/img/Actividades/Golf.jpg');
INSERT INTO actividades (nombre, categoria, pais, precio, fecha, descripcion, imagen) VALUES ('Kayak en Argentina', 'Kayak', 'Argentina', 762.0, '2025-06-21', 'Desciende por los ríos de Argentina en kayak, disfrutando de paisajes de ensueño y una gran aventura.', '/img/Actividades/Kayak.jpg');
INSERT INTO actividades (nombre, categoria, pais, precio, fecha, descripcion, imagen) VALUES ('Crossfit en Italia', 'Crossfit', 'Italia', 251.0, '2024-05-30', 'Entrena Crossfit en Italia, rodeado de historia y paisajes impresionantes mientras superas tus límites.', '/img/Actividades/Crossfit.jpg');